{% set name = "py" %}
{% set version = "1.8.2" %}
{% set hash = "f3b3a4c36512a4c4f024041ab51866f11761cc169670204b235f6b20523d4e6b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/py/py-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - pip
    - python
    - setuptools_scm
  run:
    - python

test:
  imports:
    - py
    - py.code
    - py.io
    - py.log
    - py.path
    - py.process

about:
  home: https://github.com/pytest-dev/py
  license: MIT
  license_file: LICENSE
  summary: library with cross-python path, ini-parsing, io, code, log facilities
  description: |
    The py lib is a Python development support library featuring the following
    tools and modules:
    py.path: uniform local and svn path objects
    py.apipkg: explicit API control and lazy-importing
    py.iniconfig: easy parsing of .ini files
    py.code: dynamic code generation and introspection
  doc_url: http://pylib.readthedocs.org/en/latest/
  dev_url: https://bitbucket.org/pytest-dev/py

extra:
  recipe-maintainers:
    - nicoddemus
    - jakirkham
