{% set name = "py" %}
{% set version = "1.5.1" %}
{% set hash_type = "sha256" %}
{% set hash = "e85aaa3c2e837413c6387eb2a4efbe7ff93658813d13986da004984ffe84b3a3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/py/py-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - py
    - py.code
    - py.io
    - py.log
    - py.path
    - py.process

about:
  home: https://github.com/pytest-dev/py
  license: MIT
  license_file: LICENSE
  summary: "library with cross-python path, ini-parsing, io, code, log facilities"

extra:
  recipe-maintainers:
    - nicoddemus
    - jakirkham
