travis:
  secure:
    BINSTAR_TOKEN: WlS30bguSk8YOUDLjRNiXla20H5RHEjjt74bk6W4/f6QvpojR0AeytKGC5ADMsA93uxK7lAzHs6K0Te+x8chYHe2QDFrPCYhJGI1hpUbLIUz18EvvSOxHwMMNvnT8tR4WJ4eG2HPnciUKNj6/tWUd0eiLRiSPuhjVHMncBp+dRymJn1fTj/EdRh4k3b9ysFr8jH1FCaMMGFm9LJvEffl84dMVfE8JJ02BdOapQySTS81pOoOqY7ILldd4Qtyh6POD1EMmQvFdoEfYMBckS8nlSF5hNVzgGsWbNPz2wSIWNDtKH6qfB4xkmpcvrDeh7RZm/7TQKOpuR8W+r5pQg7iC3z6kQmxTFD6VIs4BdhcBKaVj7zm6OQRcnLsbZVExXxIIO6dSecbCUDsn/r9hiY1gVyVIFfN7kdg9LDde4y6k2fxusLdvz5xpWNL1tPFEWpWGxZLaoK7ool6IiTSbBm3Sf9k3AXLZgcICKiuWl5A9LFxqpt7IjY1A5/FTULhb7i+9dXDMee/KFhvEyuRnRMX8yWLhMTnMSoVkgOFCfDWYJsFUa9xfsMZB9aLWHgxt/MFPQHoWpWAy8dUeI9My3CvOsZxo72YGEf6qOyoO+d8iNbHtWXSquI3B96SarZTS22RUevsa1qpUkAK2KZ2lK4tXVg6KHGbH0qnG2yoTtYGS5A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
