travis:
  secure:
    BINSTAR_TOKEN: hpOANAZQxnOEArtAE2awAosKpOlB9f7IheFSt5wPFzKvDZjZ6S6Q894uNPnSs5tr94qNDKuncWC+U4RkDa6CJ0nfmPCeM1nZtZ7h3Y3W3OOONomsCvbf9iGSe02wmULinBolx4V2EGMrfghuAiigOXPW7A/MFI8fV7/Ov/QMuyTjnT6WztSAh/PftvzLcmjVMZS/zVosffzCUdxjF+V5W5MmxwU85IllRj8veThSL5rHvf6TJVQ70t4qZRK1EeMe9palV0f7FPO96t9HxSZvQGnf/tkaCMlnj/kZkUrx75gP3Eurjzdg8NeskebKLIg8ZnznC/ljANVgorNOv/ETRaHcsYU7pa4qO4C8Qdmof8eTWBv7U9ZF8Z5a2qNkJ5sdJya7MQYRliEZCPd6e+dwrcK/vyZYX2mdcZjYbG7u+DZVrA0zqZ9uCS457eH8nUwkicg6r+X/HRgzEMSMSMiJn2JyT3OsapeHT9H9GACgvmQ6wtg6Zt/NPcK0bR6ARxLy9VqgdPLJtrAW6vPlGXbwiJDq0uhLtKh6Hfc1lD53ljMJXn9VYm9gQ+Uzx/bh7xjHZ0pz10kGoJ1M/wDnwH5G51QZ67W/at5kVzV3UaJCEanMZ9w6EDNPQRLLH3s7VJ9gCa69x1R2MeJPwznUypGGDL6sxz/QBsgia/5NG/On5gc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
